### ISSUE TITLE
License "All Rights Reserved"

### ISSUE THREAD

**Issue by iennae** [karthik-altiscale/iproute2-cookbook#23]
Currently the license for this cookbook is "All Rights Reserved". Is that intentional? Asking as you've published to the Supermarket which generally means you wanted to share. 

As a side, If you use the chef generate cookbook COOKBOOKNAME, if you give a -i LICENSE at the end it will auto generate the appropriate contents for LICENSE, metadata.rb and the initial recipe. Otherwise it defaults to All Rights Reserved.

**Comment by karthik-altiscale** [comment]
woops . sorry that was not intentional. it should be apache2 
PR: https://github.com/karthik-altiscale/iproute2-cookbook/pull/24
